// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bugtracker.proxies;

public enum Enumeration_IssueState
{
	In_Progress(new java.lang.String[][] { new java.lang.String[] { "en_US", "In Progress" } }),
	Open(new java.lang.String[][] { new java.lang.String[] { "en_US", "Open" } }),
	Closed(new java.lang.String[][] { new java.lang.String[] { "en_US", "Closed" } }),
	Waiting(new java.lang.String[][] { new java.lang.String[] { "en_US", "Waiting" } }),
	Duplicate(new java.lang.String[][] { new java.lang.String[] { "en_US", "Duplicate" } }),
	Rejected(new java.lang.String[][] { new java.lang.String[] { "en_US", "Rejected" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enumeration_IssueState(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
