// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bugtracker.proxies;

public enum Enumeration_ProjectDepartment
{
	Manufacturing(new java.lang.String[][] { new java.lang.String[] { "en_US", "Manufacturing" } }),
	IT(new java.lang.String[][] { new java.lang.String[] { "en_US", "IT" } }),
	Design(new java.lang.String[][] { new java.lang.String[] { "en_US", "Design" } }),
	Standardization(new java.lang.String[][] { new java.lang.String[] { "en_US", "Standardization" } }),
	Safety_Compliance(new java.lang.String[][] { new java.lang.String[] { "en_US", "Safety Compliance" } });

	private java.util.Map<java.lang.String, java.lang.String> captions;

	private Enumeration_ProjectDepartment(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<java.lang.String, java.lang.String>();
		for (java.lang.String[] captionString : captionStrings)
			captions.put(captionString[0], captionString[1]);
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		if (captions.containsKey(languageCode))
			return captions.get(languageCode);
		return captions.get("en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
