// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package bugtracker.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the BugTracker module
	public static boolean aCT_generate_id(IContext context, bugtracker.proxies.Issue _issue)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Issue", _issue == null ? null : _issue.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("BugTracker.ACT_generate_id").withParams(params).execute(context);
	}
}